spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: projet-service
          uri: http://localhost:8082
          predicates:
            - Path=/projets/**
        #          filters:
        #            - AuthenticationFilter

        - id: tache-service
          uri: http://localhost:8083
          predicates:
            - Path=/taches/**
          filters:
            - AuthenticationFilter

        - id: ressource-service
          uri: http://localhost:8084
          predicates:
            - Path=/ressources/**
          filters:
            - AuthenticationFilter

        - id: user-management
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

    discovery:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

server:
  port: 8020
