
services:
  psql1-db:
    image: postgres
    container_name: psql1-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=projets
    ports:
      - '5432:5432'
    networks:
      - zouhayr-network

  projet:
    container_name: projet_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql1-db:5432/projets
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - psql1-db
    networks:
      - zouhayr-network


networks:
  zouhayr-network:
    external: true
